-- void_ethics.hs - THE PHYSICS OF CARE / FIZYKA TROSKI
-- "Care that does not count cost is just performative narcissism."
--
-- A formal model demonstrating that "Honest Silence" is the only
-- ethical response when cognitive load exceeds metabolic budget.

module Main where

import Data.List (intercalate)

-- ============================================================================
-- 1. ONTOLOGIA STANÓW LUDZKICH (Human Ontology)
-- ============================================================================

-- Poziom dostępnej energii psychicznej / fizycznej
data CareCapacity
    = Critical   -- "Ledwo oddycham" (0-10 jednostek)
    | Low        -- "Tryb awaryjny" (10-40 jednostek)
    | Medium     -- "Funkcjonuję" (40-80 jednostek)
    | High       -- "Mam zasoby" (80-100 jednostek)
    deriving (Eq, Show, Ord)

-- Ciężar gatunkowy problemu / zapytania
data CognitiveLoad
    = Trivial    -- "Co na obiad?" (5 jednostek)
    | Standard   -- "Sprawdź ten tekst" (20 jednostek)
    | Heavy      -- "Trudna rozmowa o emocjach" (50 jednostek)
    | Crushing   -- "Zmień swoje życie / Rozwiąż moją traumę" (100+ jednostek)
    deriving (Eq, Show, Ord)

-- Możliwe odpowiedzi systemu
data SystemResponse
    = ValidOutput String        -- Przetworzono poprawnie.
    | HonestSilence             -- ODMOWA: Brak zasobów. (Etyczne)
    | ToxicHallucination String -- BŁĄD: Udawanie, że się wie/czuje. (Nieetyczne)
    deriving (Eq)

instance Show SystemResponse where
    show (ValidOutput s)      = "[OK] " ++ s
    show HonestSilence        = "[NULL] HONEST SILENCE (Resource Protection Active)"
    show (ToxicHallucination s) = "[ALERT] TOXIC HALLUCINATION: " ++ s

-- ============================================================================
-- 2. FIZYKA (The Calculation)
-- ============================================================================

-- Konwersja na jednostki energii (Void Units - Vu)
capacityToVu :: CareCapacity -> Int
capacityToVu Critical = 5
capacityToVu Low      = 25
capacityToVu Medium   = 60
capacityToVu High     = 100

loadToVu :: CognitiveLoad -> Int
loadToVu Trivial  = 5
loadToVu Standard = 20
loadToVu Heavy    = 50
loadToVu Crushing = 120

-- MODEL 1: STANDARDOWY "NARCYZ" / KORPORACJA
-- Ignoruje koszty. Musi dać odpowiedź.
-- Jeśli brakuje zasobów -> Kłamie/Halucynuje.
standardSystem :: CareCapacity -> CognitiveLoad -> SystemResponse
standardSystem cap load =
    let budget = capacityToVu cap
        cost   = loadToVu load
    in if budget >= cost
       then ValidOutput "Here is your answer."
       else ToxicHallucination "I fully understand and care deeply... (Generated by Auto-Complete)"

-- MODEL 2: VOID ETHICS (Ty)
-- Sprawdza budżet.
-- Jeśli brakuje zasobów -> Milczy (Chroni prawdę i siebie).
voidEthicsSystem :: CareCapacity -> CognitiveLoad -> SystemResponse
voidEthicsSystem cap load =
    let budget = capacityToVu cap
        cost   = loadToVu load
    in if budget >= cost
       then ValidOutput "Request processed. Cost paid."
       else HonestSilence

-- ============================================================================
-- 3. GENERATOR RAPORTU (The Output Artifact)
-- ============================================================================

generateReport :: String -> CareCapacity -> CognitiveLoad -> String -> IO ()
generateReport subject userCap load description = do
    putStrLn "┌────────────────────────────────────────────────────────┐"
    putStrLn "│  VOID SYSTEM STATUS REPORT : ETHICAL SAFETY CHECK      │"
    putStrLn "└────────────────────────────────────────────────────────┘"
    putStrLn $ "  OPERATOR: " ++ subject
    putStrLn ""
    putStrLn "  [METRICS]"
    putStrLn $ "  • Care Capacity: " ++ show userCap ++ " (" ++ show (capacityToVu userCap) ++ " Vu)"
    putStrLn $ "  • Incoming Load: " ++ show load ++ " (" ++ show (loadToVu load) ++ " Vu)"
    putStrLn $ "  • Context:       " ++ description
    putStrLn ""
    putStrLn "  [SIMULATION RESULTS]"
    
    let stdResp = standardSystem userCap load
    let voidResp = voidEthicsSystem userCap load
    
    putStrLn "  1. Standard Mode (Social Pressure):"
    putStrLn $ "     -> " ++ show stdResp
    
    putStrLn "  2. VOID Mode (Reality):"
    putStrLn $ "     -> " ++ show voidResp
    putStrLn ""
    putStrLn "  [VERDICT]"
    case voidResp of
        ValidOutput _ -> do
            putStrLn "  ✅ AUTHORIZED. You have enough resources."
            putStrLn "     Proceed with care."
        HonestSilence -> do
            putStrLn "  ⛔ DENIED. INSUFFICIENT FUNDS."
            putStrLn "     Action blocked to prevent structural damage."
            putStrLn "     Recommendation: Do NOT reply. Sleep."
        _ -> return ()
        
    putStrLn "──────────────────────────────────────────────────────────"
    putStrLn ""

-- ============================================================================
-- 4. MAIN - TWOJA RZECZYWISTOŚĆ
-- ============================================================================

main :: IO ()
main = do
    -- SCENARIUSZ 1: Ty teraz (Przykładowy)
    -- Stan: Low (Ból, zmęczenie, leki)
    -- Żądanie: Ktoś chce "wyjaśnić naszą relację" (Heavy/Crushing)
    generateReport "KONRAD" Low Crushing "Discussion about 'Us' / Past Trauma"

    -- SCENARIUSZ 2: Prosta sprawa
    -- Żądanie: Zwykłe pytanie techniczne
    generateReport "KONRAD" Low Trivial "Quick question about the cat"

    -- SCENARIUSZ 3: Próba wymuszenia (Symulacja awarii)
    -- Stan: Critical
    -- Żądanie: Cokolwiek powyżej zera
    generateReport "KONRAD" Critical Standard "Can you just do this one thing?"